export const questionAnswerData = [
  {
    id: 1,
    group: 'Hi! What are you looking for today?',
    question_answer: 'Hi! What are you looking for today?',
    nodeName: "Intro",
    node_category: 'Inquiry',
    status: 'Active',
    created_on: new Date(2018, 6, 10),
    last_modified_on: new Date(2019, 2, 15),
    last_modified_by: 'AlexiaSmith',
    visible: true,
    clientName: 'Eskaton',
    franchiseName: ['FreshFusion'],
  },
  {
    id: 2,
    group: 'Hi! What are you looking for today?',
    question_answer: 'Pricing information',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 6, 10),
    last_modified_on: new Date(2019, 2, 15),
    last_modified_by: 'AlexiaSmith',
    visible: true,
  },
  {
    id: 3,
    group: 'Hi! What are you looking for today?',
    question_answer: 'Schedule a tour',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 6, 10),
    last_modified_on: new Date(2019, 2, 15),
    last_modified_by: 'AlexiaSmith',
    visible: true
  },
  {
    id: 4,
    group: 'Hi! What are you looking for today?',
    question_answer: 'Speak with an advisor',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 6, 10),
    last_modified_on: new Date(2019, 2, 15),
    last_modified_by: 'AlexiaSmith'
  },
  {
    id: 5,
    group: 'Hi! What are you looking for today?',
    question_answer: 'I’m researching my options',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 6, 10),
    last_modified_on: new Date(2019, 2, 15),
    last_modified_by: 'AlexiaSmith'
  },
  {
    id: 6,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'Who are you researching senior living options for today?',
    nodeName: "Full name",
    node_category: 'Name',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson',
    clientName: 'Cascade Living Group',
    franchiseName: ['GreenGrove Cafe'],

  },
  {
    id: 7,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'A Parent',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson'
  },
  {
    id: 8,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'Myslef',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson'
  },
  {
    id: 9,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'My spouse or partner',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson'
  },
  {
    id: 10,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'Someone else',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson'
  },
  {
    id: 11,
    group: 'Who are you researching senior living options for today?',
    question_answer: 'I’d like to skip these questions for now',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2018, 9, 19),
    last_modified_on: new Date(2020, 4, 26),
    last_modified_by: 'MaxJohnson'
  },
  {
    id: 12,
    group: 'Ok, thanks. Why do you think it might be time to consider a move to a senior living community? You can choose more than one.',
    question_answer: 'Ok, thanks. Why do you think it might be time to consider a move to a senior living community? You can choose more than one.',
    nodeName: "Full name -1",
    node_category: 'Name',
    status: 'Inactive',
    created_on: new Date(2019, 2, 4),
    last_modified_on: new Date(2019, 8, 11),
    last_modified_by: 'SophiaDavis',
    clientName: 'Brightview Senior Living',
    franchiseName: ['Sunrise Bites'],

  },
  {
    id: 13,
    group: 'Ok, thanks. Why do you think it might be time to consider a move to a senior living community? You can choose more than one.',
    question_answer: 'Just curious about options',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 2, 4),
    last_modified_on: new Date(2019, 8, 11),
    last_modified_by: 'SophiaDavis'
  },
  {
    id: 14,
    group: 'Ok, thanks. Why do you think it might be time to consider a move to a senior living community? You can choose more than one.',
    question_answer: 'Thinking about downsizing',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 2, 4),
    last_modified_on: new Date(2019, 8, 11),
    last_modified_by: 'SophiaDavis'
  },

  {
    id: 15,
    group: 'How soon are you looking to make a decision?',
    question_answer: 'How soon are you looking to make a decision?',
    nodeName: "Full name -2",
    node_category: 'Name',
    status: 'Inactive',
    created_on: new Date(2019, 6, 27),
    last_modified_on: new Date(2022, 3, 20),
    last_modified_by: 'LucasMiller',
    clientName: 'Blake Management Group',
    franchiseName: ['UrbanEats' , 'Tasty Trails'],

  },
  {
    id: 16,
    group: 'How soon are you looking to make a decision?',
    question_answer: 'Within the next month',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 6, 27),
    last_modified_on: new Date(2022, 3, 20),
    last_modified_by: 'LucasMiller',
  },
  {
    id: 17,
    group: 'How soon are you looking to make a decision?',
    question_answer: 'Within the next three month',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 6, 27),
    last_modified_on: new Date(2022, 3, 20),
    last_modified_by: 'LucasMiller'
  },
  {
    id: 18,
    group: 'What are your preferences for accommodation size?',
    question_answer: 'What are your preferences for accommodation size?',
    nodeName: "Full name -3",
    node_category: 'Name',
    status: 'Active',
    created_on: new Date(2019, 7, 12),
    last_modified_on: new Date(2020, 4, 13),
    last_modified_by: 'OliviaClark',
    clientName: 'Eskaton',
    franchiseName: ['GreenGrove Cafe'],
  },
  {
    id: 19,
    group: 'What are your preferences for accommodation size?',
    question_answer: 'Shared accommodation',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2019, 7, 12),
    last_modified_on: new Date(2020, 4, 13),
    last_modified_by: 'OliviaClark'
  },
  {
    id: 20,
    group: 'What industry or sector are you interested in for a franchise?',
    question_answer: 'What industry or sector are you interested in for a franchise?',
    nodeName: "Full name -4",
    node_category: 'Name',
    status: 'Inactive',
    created_on: new Date(2019, 12, 27),
    last_modified_on: new Date(2021, 7, 21),
    last_modified_by: 'EthanBrown',
    clientName: 'Eskaton',
    franchiseName: ['Wholesome Harvest'],
  },
  {
    id: 21,
    group: 'What industry or sector are you interested in for a franchise?',
    question_answer: 'Retail',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 12, 27),
    last_modified_on: new Date(2021, 7, 21),
    last_modified_by: 'EthanBrown'
  },
  {
    id: 22,
    group: 'What industry or sector are you interested in for a franchise?',
    question_answer: 'Education',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 12, 27),
    last_modified_on: new Date(2021, 7, 21),
    last_modified_by: 'EthanBrown'
  },
  {
    id: 23,
    group: 'What industry or sector are you interested in for a franchise?',
    question_answer: 'Halth and wellness',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2019, 12, 27),
    last_modified_on: new Date(2021, 7, 21),
    last_modified_by: 'EthanBrown'
  },
  {
    id: 24,
    group: 'Are you interested in a specific franchise brand or company?',
    question_answer: 'Are you interested in a specific franchise brand or company?',
    nodeName: "Motivations",
    node_category: 'Contact preference',
    status: 'Active',
    created_on: new Date(2020, 4, 15),
    last_modified_on: new Date(2020, 8, 11),
    last_modified_by: 'AvaWilson',
    clientName: 'Cascade Living Group',
    franchiseName: ['WSizzle & Sip, Savor & Spice'],
  },
  {
    id: 25,
    group: 'Are you interested in a specific franchise brand or company?',
    question_answer: 'No Reply',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2020, 4, 15),
    last_modified_on: new Date(2020, 8, 11),
    last_modified_by: 'AvaWilson'
  },
  {
    id: 26,
    group: 'What is your level of investment capital for a franchise opportunity?',
    question_answer: 'What is your level of investment capital for a franchise opportunity?',
    nodeName: "Motivations - 1",
    node_category: 'Contact preference',
    status: 'Active',
    created_on: new Date(2020, 8, 4),
    last_modified_on: new Date(2020, 3, 6),
    last_modified_by: 'KaiLee',
    clientName: 'Brightview Senior Living',
    franchiseName: ['Crisp Cravings']
  },
  {
    id: 27,
    group: 'What is your level of investment capital for a franchise opportunity?',
    question_answer: 'Less than $50,000',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2020, 8, 4),
    last_modified_on: new Date(2020, 3, 6),
    last_modified_by: 'KaiLee'
  },
  {
    id: 28,
    group: 'What is your level of investment capital for a franchise opportunity?',
    question_answer: '$50,000 to $100,000',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2020, 8, 4),
    last_modified_on: new Date(2020, 3, 6),
    last_modified_by: 'KaiLee'
  },
  {
    id: 29,
    group: 'Are you interested in a single-unit franchise or a multi-unit franchise?',
    question_answer: 'Are you interested in a single-unit franchise or a multi-unit franchise?',
    nodeName: "Motivations -2",
    node_category: 'Contact preference',
    status: 'Active',
    created_on: new Date(2020, 9, 13),
    last_modified_on: new Date(2021, 8, 26),
    last_modified_by: 'Alice',
    clientName: 'GreenFields',
    franchiseName: ['Crafty Crust'],
  },
  {
    id: 30,
    group: 'Are you interested in a single-unit franchise or a multi-unit franchise?',
    question_answer: 'Yes',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2020, 9, 13),
    last_modified_on: new Date(2021, 8, 26),
    last_modified_by: 'Alice'
  },
  {
    id: 31,
    group: 'Are you interested in a single-unit franchise or a multi-unit franchise?',
    question_answer: 'No',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2020, 9, 13),
    last_modified_on: new Date(2021, 8, 26),
    last_modified_by: 'Alice'
  },
  {
    id: 32,
    group: 'What geographic location or region are you considering',
    question_answer: 'What geographic location or region are you considering',
    nodeName: "Motivations -3",
    node_category: 'Contact preference',
    status: 'Inactive',
    created_on: new Date(2020, 11, 21),
    last_modified_on: new Date(2020, 12, 27),
    last_modified_by: 'John',
    clientName: 'Eskaton',
    franchiseName: ['Bakery Bliss'],
  },
  {
    id: 33,
    group: 'What geographic location or region are you considering',
    question_answer: 'Local area (city or town)',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2020, 11, 21),
    last_modified_on: new Date(2020, 12, 27),
    last_modified_by: 'John'
  },
  {
    id: 34,
    group: 'What geographic location or region are you considering',
    question_answer: 'State or province',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2020, 11, 21),
    last_modified_on: new Date(2020, 12, 27),
    last_modified_by: 'John'
  },
  {
    id: 35,
    group: 'What level of support are you seeking from a franchise company?',
    question_answer: 'What level of support are you seeking from a franchise company?',
    nodeName: "Motivations -4",
    node_category: 'Contact preference',
    status: 'Active',
    created_on: new Date(2021, 1, 1),
    last_modified_on: new Date(2022, 9, 4),
    last_modified_by: 'Darth',
    clientName: 'Blake Management Group',
    franchiseName: ['FlavorFusion']
  },
  {
    id: 36,
    group: 'What level of support are you seeking from a franchise company?',
    question_answer: 'No Reply',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2021, 1, 1),
    last_modified_on: new Date(2022, 9, 4),
    last_modified_by: 'Darth'
  },
  {
    id: 37,
    group: 'What motivated you to consider purchasing a franchise?',
    question_answer: 'What motivated you to consider purchasing a franchise?',
    nodeName: "Level of care",
    node_category: 'Service level',
    status: 'Active',
    created_on: new Date(2021, 5, 29),
    last_modified_on: new Date(2023, 6, 23),
    last_modified_by: 'JayLyn',
    clientName: 'Eskaton',
    franchiseName: ['Bakery Bliss'],
  },
  {
    id: 38,
    group: 'What motivated you to consider purchasing a franchise?',
    question_answer: 'Attracted to proven business model',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2021, 5, 29),
    last_modified_on: new Date(2023, 6, 23),
    last_modified_by: 'JayLyn'
  },
  {
    id: 39,
    group: 'What motivated you to consider purchasing a franchise?',
    question_answer: 'Interest in a specific industry or brand',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2021, 5, 29),
    last_modified_on: new Date(2023, 6, 23),
    last_modified_by: 'JayLyn'
  },
  {
    id: 40,
    group: 'What is your level of experience in the industry or business ownership?',
    question_answer: 'What is your level of experience in the industry or business ownership?',
    nodeName: "Level of care -1",
    node_category: 'Service level',
    status: 'Inactive',
    created_on: new Date(2021, 11, 13),
    last_modified_on: new Date(2022, 12, 17),
    last_modified_by: 'BenCruz',
    clientName: 'Cascade Living Group',
    franchiseName: ['SweetScape, VeggieVille']
  },
  {
    id: 41,
    group: 'What is your level of experience in the industry or business ownership?',
    question_answer: 'Extensive experience',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2021, 11, 13),
    last_modified_on: new Date(2022, 12, 17),
    last_modified_by: 'BenCruz'
  },
  {
    id: 42,
    group: 'Are you interested in a franchise resale opportunity?',
    question_answer: 'Are you interested in a franchise resale opportunity?',
    nodeName: "Level of care -2",
    node_category: 'Service level',
    status: 'Active',
    created_on: new Date(2022, 8, 16),
    last_modified_on: new Date(2022, 2, 7),
    last_modified_by: 'Mia Roberts',
    clientName: 'Brightview Senior Living',
    franchiseName: ['Tasty Trails']
  },
  {
    id: 43,
    group: 'Are you interested in a franchise resale opportunity?',
    question_answer: 'No Reply',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2022, 8, 16),
    last_modified_on: new Date(2022, 2, 7),
    last_modified_by: 'Mia Roberts'
  },

  {
    id: 44,
    group: 'What type of support are you looking for from the franchisor?',
    question_answer: 'What type of support are you looking for from the franchisor?',
    nodeName: "Level of care -3",
    node_category: 'Service level',
    status: 'Active',
    created_on: new Date(2023, 4, 6),
    last_modified_on: new Date(2023, 10, 27),
    last_modified_by: 'Wilson',
    clientName: 'GreenFields',
    franchiseName: ['UrbanEats']
  },
  {
    id: 45,
    group: 'What type of support are you looking for from the franchisor?',
    question_answer: 'Comprehensive support',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2023, 4, 6),
    last_modified_on: new Date(2023, 10, 27),
    last_modified_by: 'Wilson'
  },
  {
    id: 46,
    group: 'What type of support are you looking for from the franchisor?',
    question_answer: 'Guidance and recommendations',
    nodeName: '',
    node_category: '',
    status: 'Active',
    created_on: new Date(2023, 4, 6),
    last_modified_on: new Date(2023, 10, 27),
    last_modified_by: 'Wilson'
  },
  {
    id: 47,
    group: 'How important is ongoing innovation and adaptation to market trends?',
    question_answer: 'How important is ongoing innovation and adaptation to market trends?',
    nodeName: "Level of care -4",
    node_category: 'Service level',
    status: 'Inactive',
    created_on: new Date(2024, 1, 30),
    last_modified_on: new Date(2024, 4, 19),
    last_modified_by: 'MaxKai',
    clientName: 'Brightview Senior Living',
    franchiseName: ['Nourish Nation']
  },
  {
    id: 48,
    group: 'How important is ongoing innovation and adaptation to market trends?',
    question_answer: 'Extremely important,',
    nodeName: '',
    node_category: '',
    status: 'Inactive',
    created_on: new Date(2024, 1, 30),
    last_modified_on: new Date(2024, 4, 19),
    last_modified_by: 'MaxKai'
  },
];